"""otp added to user

Revision ID: 04a109b8f370
Revises: ec572b4a1f27
Create Date: 2026-07-20 00:47:27.310430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04a109b8f370'
down_revision: Union[str, Sequence[str], None] = 'ec572b4a1f27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('otp_key', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('otp_expire', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'otp_expire')
    op.drop_column('users', 'otp_key')
    # ### end Alembic commands ###
