"""idompotent_key added to order

Revision ID: 60bd23bbf79d
Revises: 9a068b72f4b9
Create Date: 2026-07-18 21:38:13.654702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60bd23bbf79d'
down_revision: Union[str, Sequence[str], None] = '9a068b72f4b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('idompotent_key', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_orders_idompotent_key'), 'orders', ['idompotent_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_idompotent_key'), table_name='orders')
    op.drop_column('orders', 'idompotent_key')
    # ### end Alembic commands ###
