"""address table added

Revision ID: 946608b12df9
Revises: 60bd23bbf79d
Create Date: 2026-07-19 09:42:54.158479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '946608b12df9'
down_revision: Union[str, Sequence[str], None] = '60bd23bbf79d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('landmark', sa.String(), nullable=True),
    sa.Column('zip_code', sa.Integer(), nullable=False),
    sa.Column('line_1', sa.String(), nullable=False),
    sa.Column('line_2', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_addresses_address_id'), 'addresses', ['address_id'], unique=True)
    op.add_column('orders', sa.Column('delivery_addr_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'orders', 'addresses', ['delivery_addr_id'], ['address_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'delivery_addr_id')
    op.drop_index(op.f('ix_addresses_address_id'), table_name='addresses')
    op.drop_table('addresses')
    # ### end Alembic commands ###
