"""option column added to attribute key

Revision ID: e410e318e89d
Revises: b76eda910895
Create Date: 2026-07-17 14:04:40.049390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e410e318e89d'
down_revision: Union[str, Sequence[str], None] = 'b76eda910895'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attribute_keys', sa.Column('options', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attribute_keys', 'options')
    # ### end Alembic commands ###
