"""address table added

Revision ID: ee713868bcb7
Revises: 946608b12df9
Create Date: 2026-07-19 10:11:00.860983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee713868bcb7'
down_revision: Union[str, Sequence[str], None] = '946608b12df9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addresses', sa.Column('deleted', sa.Boolean(), nullable=True))
    op.add_column('addresses', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('addresses', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('addresses', 'created_at')
    op.drop_column('addresses', 'deleted_at')
    op.drop_column('addresses', 'deleted')
    # ### end Alembic commands ###
