"""otp removed from user

Revision ID: ff8b7ad6e0f6
Revises: 04a109b8f370
Create Date: 2026-07-20 00:54:56.591727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ff8b7ad6e0f6'
down_revision: Union[str, Sequence[str], None] = '04a109b8f370'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'otp_expire')
    op.drop_column('users', 'otp_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('otp_key', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('otp_expire', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
