state_city = {
    "Abia": ["Aba", "Umuahia", "Ohafia", "Arochukwu", "Abiriba"],
    "Adamawa": ["Yola", "Mubi", "Numan", "Michika", "Ganye"],
    "Akwa Ibom": ["Uyo", "Eket", "Ikot Ekpene", "Oron", "Ibeno"],
    "Anambra": ["Awka", "Onitsha", "Nnewi", "Ekwulobia", "Ihiala"],
    "Bauchi": ["Bauchi", "Azare", "Misau", "Jama'are", "Ning"],
    "Bayelsa": ["Yenagoa", "Brass", "Amassoma", "Ogbia", "Sagbama"],
    "Benue": ["Makurdi", "Gboko", "Otukpo", "Katsina-Ala", "Zaki Biam"],
    "Borno": ["Maiduguri", "Biu", "Bama", "Gwoza", "Dikwa"],
    "Cross River": ["Calabar", "Ikom", "Ogoja", "Obudu", "Ugep"],
    "Delta": ["Asaba", "Warri", "Sapele", "Ughelli", "Agbor"],
    "Ebonyi": ["Abakaliki", "Afikpo", "Onueke", "Edda", "Ugbodo"],
    "Edo": ["Benin City", "Auchi", "Uromi", "Ekpoma", "Igarra"],
    "Ekiti": ["Ado Ekiti", "Ikere Ekiti", "Oye Ekiti", "Efon Alaaye", "Aramoko Ekiti"],
    "Enugu": ["Enugu", "Nsukka", "Oji River", "Awgu", "Udi"],
    "Federal Capital Territory": ["Abuja", "Gwagwalada", "Kuje", "Bwari", "Abaji"],
    "Gombe": ["Gombe", "Kaltungo", "Dukin", "Billiri", "Bajoga"],
    "Imo": ["Owerri", "Orlu", "Okigwe", "Oguta", "Mbaise"],
    "Jigawa": ["Dutse", "Hadejia", "Kazaure", "Gumel", "Ringim"],
    "Kaduna": ["Kaduna", "Zaria", "Kafanchan", "Kagoro", "Zonkwa"],
    "Kano": ["Kano", "Wudil", "Rano", "Bichi", "Dambatta"],
    "Katsina": ["Katsina", "Daura", "Funtua", "Malumfashi", "Kankia"],
    "Kebbi": ["Birnin Kebbi", "Argungu", "Yauri", "Zuru", "Gwandu"],
    "Kogi": ["Lokoja", "Okene", "Idah", "Anyigba", "Kabba"],
    "Kwara": ["Ilorin", "Offa", "Omu-Aran", "Jebba", "Patigi"],
    "Lagos": ["Lagos", "Ikeja", "Ikorodu", "Epe", "Badagry"],
    "Nasarawa": ["Lafia", "Keffi", "Karu", "Akwanga", "Nasarawa"],
    "Niger": ["Minna", "Bida", "Suleja", "Kontagora", "Lapai"],
    "Ogun": ["Abeokuta", "Ijebu Ode", "Sagamu", "Ota", "Ilaro"],
    "Ondo": ["Akure", "Ondo City", "Owo", "Ikare", "Okitipupa"],
    "Osun": ["Osogbo", "Ile-Ife", "Ilesa", "Ede", "Iwo"],
    "Oyo": ["Ibadan", "Ogbomoso", "Oyo", "Iseyin", "Saki"],
    "Plateau": ["Jos", "Bukuru", "Pankshin", "Shendam", "Barkin Ladi"],
    "Rivers": ["Port Harcourt", "Obio-Akpor", "Bonny", "Ahoada", "Degema"],
    "Sokoto": ["Sokoto", "Tambuwal", "Wamako", "Gwadabawa", "Illela"],
    "Taraba": ["Jalingo", "Wukari", "Bali", "Gembu", "Mutum Biyu"],
    "Yobe": ["Damaturu", "Gashua", "Nguru", "Potiskum", "Geidam"],
    "Zamfara": ["Gusau", "Kaura Namoda", "Talata Mafara", "Anka", "Maru"]
}
